-- AlterTable
ALTER TABLE "User" ADD COLUMN     "LastOpened" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP;

-- CreateTable
CREATE TABLE "FlowView" (
    "FlowViewID" SERIAL NOT NULL,
    "CreatedTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "FK_FlowID" TEXT,
    "FK_UserID" INTEGER,

    CONSTRAINT "FlowView_pkey" PRIMARY KEY ("FlowViewID")
);

-- AddForeignKey
ALTER TABLE "FlowView" ADD CONSTRAINT "FlowView_FK_UserID_fkey" FOREIGN KEY ("FK_UserID") REFERENCES "User"("UserID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlowView" ADD CONSTRAINT "FlowView_FK_FlowID_fkey" FOREIGN KEY ("FK_FlowID") REFERENCES "Flow"("FlowID") ON DELETE SET NULL ON UPDATE CASCADE;
