/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"


declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  EnumVisibilityNullableFilter: { // input type
    equals?: NexusGenEnums['Visibility'] | null; // Visibility
    in?: NexusGenEnums['Visibility'][] | null; // [Visibility!]
    not?: NexusGenInputs['NestedEnumVisibilityNullableFilter'] | null; // NestedEnumVisibilityNullableFilter
    notIn?: NexusGenEnums['Visibility'][] | null; // [Visibility!]
  }
  FlowCreateManyCreatedByUserInput: { // input type
    Body?: string | null; // String
    CreatedTime?: NexusGenScalars['DateTime'] | null; // DateTime
    FlowID?: number | null; // Int
    Title?: string | null; // String
    Visibility?: NexusGenEnums['Visibility'] | null; // Visibility
  }
  FlowCreateManyCreatedByUserInputEnvelope: { // input type
    data?: NexusGenInputs['FlowCreateManyCreatedByUserInput'][] | null; // [FlowCreateManyCreatedByUserInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  FlowCreateNestedManyWithoutCreatedByUserInput: { // input type
    connect?: NexusGenInputs['FlowWhereUniqueInput'][] | null; // [FlowWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['FlowCreateOrConnectWithoutCreatedByUserInput'][] | null; // [FlowCreateOrConnectWithoutCreatedByUserInput!]
    create?: NexusGenInputs['FlowCreateWithoutCreatedByUserInput'][] | null; // [FlowCreateWithoutCreatedByUserInput!]
    createMany?: NexusGenInputs['FlowCreateManyCreatedByUserInputEnvelope'] | null; // FlowCreateManyCreatedByUserInputEnvelope
  }
  FlowCreateOrConnectWithoutCreatedByUserInput: { // input type
    create: NexusGenInputs['FlowCreateWithoutCreatedByUserInput']; // FlowCreateWithoutCreatedByUserInput!
    where: NexusGenInputs['FlowWhereUniqueInput']; // FlowWhereUniqueInput!
  }
  FlowCreateWithoutCreatedByUserInput: { // input type
    Body?: string | null; // String
    CreatedTime?: NexusGenScalars['DateTime'] | null; // DateTime
    Title?: string | null; // String
    Visibility?: NexusGenEnums['Visibility'] | null; // Visibility
  }
  FlowListRelationFilter: { // input type
    every?: NexusGenInputs['FlowWhereInput'] | null; // FlowWhereInput
    none?: NexusGenInputs['FlowWhereInput'] | null; // FlowWhereInput
    some?: NexusGenInputs['FlowWhereInput'] | null; // FlowWhereInput
  }
  FlowOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  FlowWhereInput: { // input type
    AND?: NexusGenInputs['FlowWhereInput'][] | null; // [FlowWhereInput!]
    Body?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    CreatedById?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    CreatedByUser?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    CreatedTime?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    FlowID?: NexusGenInputs['IntFilter'] | null; // IntFilter
    NOT?: NexusGenInputs['FlowWhereInput'][] | null; // [FlowWhereInput!]
    OR?: NexusGenInputs['FlowWhereInput'][] | null; // [FlowWhereInput!]
    Title?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Visibility?: NexusGenInputs['EnumVisibilityNullableFilter'] | null; // EnumVisibilityNullableFilter
  }
  FlowWhereUniqueInput: { // input type
    FlowID?: number | null; // Int
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedEnumVisibilityNullableFilter: { // input type
    equals?: NexusGenEnums['Visibility'] | null; // Visibility
    in?: NexusGenEnums['Visibility'][] | null; // [Visibility!]
    not?: NexusGenInputs['NestedEnumVisibilityNullableFilter'] | null; // NestedEnumVisibilityNullableFilter
    notIn?: NexusGenEnums['Visibility'][] | null; // [Visibility!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  UserCreateInput: { // input type
    DisplayName?: string | null; // String
    Email: string; // String!
    Flows?: NexusGenInputs['FlowCreateNestedManyWithoutCreatedByUserInput'] | null; // FlowCreateNestedManyWithoutCreatedByUserInput
    ProfilePictureLink?: string | null; // String
    UID?: string | null; // String
  }
  UserOrderByWithRelationInput: { // input type
    DisplayName?: NexusGenEnums['SortOrder'] | null; // SortOrder
    Email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    Flows?: NexusGenInputs['FlowOrderByRelationAggregateInput'] | null; // FlowOrderByRelationAggregateInput
    ProfilePictureLink?: NexusGenEnums['SortOrder'] | null; // SortOrder
    UID?: NexusGenEnums['SortOrder'] | null; // SortOrder
    UserID?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    DisplayName?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    Email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    Flows?: NexusGenInputs['FlowListRelationFilter'] | null; // FlowListRelationFilter
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    ProfilePictureLink?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    UID?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    UserID?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  UserWhereUniqueInput: { // input type
    UserID?: number | null; // Int
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
  Visibility: "HIDDEN" | "PRIVATE" | "PUBLIC"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Flow: { // root type
    Body?: string | null; // String
    CreatedById?: number | null; // Int
    CreatedTime: NexusGenScalars['DateTime']; // DateTime!
    FlowID: number; // Int!
    Title?: string | null; // String
    Visibility?: NexusGenEnums['Visibility'] | null; // Visibility
  }
  Mutation: {};
  Query: {};
  User: { // root type
    DisplayName?: string | null; // String
    Email: string; // String!
    ProfilePictureLink?: string | null; // String
    UID?: string | null; // String
    UserID: number; // Int!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Flow: { // field return type
    Body: string | null; // String
    CreatedById: number | null; // Int
    CreatedByUser: NexusGenRootTypes['User'] | null; // User
    CreatedTime: NexusGenScalars['DateTime']; // DateTime!
    FlowID: number; // Int!
    Title: string | null; // String
    Visibility: NexusGenEnums['Visibility'] | null; // Visibility
  }
  Mutation: { // field return type
    createOneUser: NexusGenRootTypes['User']; // User!
    deleteOneUser: NexusGenRootTypes['User'] | null; // User
  }
  Query: { // field return type
    flow: NexusGenRootTypes['Flow'] | null; // Flow
    flows: NexusGenRootTypes['Flow'][]; // [Flow!]!
    user: NexusGenRootTypes['User'] | null; // User
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  User: { // field return type
    DisplayName: string | null; // String
    Email: string; // String!
    ProfilePictureLink: string | null; // String
    UID: string | null; // String
    UserID: number; // Int!
  }
}

export interface NexusGenFieldTypeNames {
  Flow: { // field return type name
    Body: 'String'
    CreatedById: 'Int'
    CreatedByUser: 'User'
    CreatedTime: 'DateTime'
    FlowID: 'Int'
    Title: 'String'
    Visibility: 'Visibility'
  }
  Mutation: { // field return type name
    createOneUser: 'User'
    deleteOneUser: 'User'
  }
  Query: { // field return type name
    flow: 'Flow'
    flows: 'Flow'
    user: 'User'
    users: 'User'
  }
  User: { // field return type name
    DisplayName: 'String'
    Email: 'String'
    ProfilePictureLink: 'String'
    UID: 'String'
    UserID: 'Int'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createOneUser: { // args
      data: NexusGenInputs['UserCreateInput']; // UserCreateInput!
    }
    deleteOneUser: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
  }
  Query: {
    flow: { // args
      where: NexusGenInputs['FlowWhereUniqueInput']; // FlowWhereUniqueInput!
    }
    flows: { // args
      after?: NexusGenInputs['FlowWhereUniqueInput'] | null; // FlowWhereUniqueInput
      before?: NexusGenInputs['FlowWhereUniqueInput'] | null; // FlowWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['FlowWhereInput'] | null; // FlowWhereInput
    }
    user: { // args
      where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['UserOrderByWithRelationInput'][] | null; // [UserOrderByWithRelationInput!]
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}